### ISSUE TITLE
Styles are not encapsulated

### ISSUE THREAD

**Issue by erasmo-marin** [catamphetamine/print-error#2]
I tried this library to pretty-print the error stack in React components using the new Error Boundaries feature. The injected styles causes my web app to look broken since it inject styles to the body element. I think the styles should be encapsulated using a class.

**Comment by catamphetamine** [comment]
What do you suggest exactly?
And what's you issue - it's also unclear.

**Comment by erasmo-marin** [comment]
I suggest to not generate an entire html document but just generate a div. I'm currently working on a fork to fix this.

The problem I'm having is that currently the script is injecting styles to the body element directly and it breaks my app design. instead of that, I added the `print-error-stack` class to the container div. Check my fork for more details, I still need to fix some styles issues since the em units are not working.

**Comment by catamphetamine** [comment]
Fixed in the latest version.
Added `htmlRenderStack(error)` and `ERROR_STACK_STYLE` exports.
Also replaced `rem`s with `%`s.
